pipeline {
    agent any

    stages {
	stage('Build Application') {
            steps {
                // Étape pour construire votre application
                script {
                    try {
                        sh 'gradle clean build'
                    } catch (Exception gradleError) {
                        echo "Gradle build failed, we will use the old build, proceeding to the next step"
                    }
                }
            }
        } 

        stage('Build Docker Image') {
            steps {
                // Étape pour construire l'image Docker
                script {
                    sh 'docker build -t covid-api .'
                }
            }
        }

        stage('Run Docker Compose') {
            steps {
                // Étape pour exécuter docker-compose
                script {
                    sh 'docker-compose up -d'
                }
            }
        }
    }
}
