version: '3'

services:
  app:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - rabbitmq

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672" # Port de l'interface de gestion
      - "5672:5672"   # Port de communication AMQP
